title: Site
icon: page

columns:
  navigation:
    width: 1/2
    sections:
      published:
        headline: Published Pages
        type: pages
        status: listed

      unlisted:
        headline: Unlisted
        type: pages
        status: unlisted
        help: Not listed in the navigation bar

      drafts:
        headline: Drafts
        type: pages
        status: draft


